In [4]:
print("Hello World")

Hello World


In [5]:
# importing numpy but using it as np in the whole code
import numpy as np
print("Package successfully imported!")

Package successfully imported!


In [6]:
# converting list to array
list_var = [1,2,3,4,5]
list_to_array = np.array(list_var)
print(list_to_array)
print(type(list_to_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
# converting tuple to array
tuple_var = (1,2,3,4,5)
tuple_to_array = np.array(tuple_var)
print(tuple_to_array)
print(type(tuple_to_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
# multidimensional array
array_2d = np.array([[1,2,3],[4,5,6]])
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [10]:
array_3d = np.array([[1,2,3],[4,5,6],[[1,2,3],[4,5,6]]])
print(array_3d)

[list([1, 2, 3]) list([4, 5, 6]) list([[1, 2, 3], [4, 5, 6]])]


/var/folders/p0/yyl2l2ps6fv1jt2sg6yk4m7c0000gn/T/ipykernel_12659/938592417.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array_3d = np.array([[1,2,3],[4,5,6],[[1,2,3],[4,5,6]]])


In [13]:
# adding 2 lists without the numpy
list1 = [1,2,3,4,5,9]
list2 = [6,7,8,9,10,11]
sum_list = []
length1 = len(list1)
length2 = len(list2)
min_length = min(length1, length2)
for i in range (0, min_length):
    sum_list.append(list1[i] + list2[i])
print(sum_list)

[7, 9, 11, 13, 15, 20]


In [14]:
# adding 2 lists buy converting them to array with the numpy
array1 = np.array([1,2,3,4,5])
array2 = np.array([6,7,8,9,10])
sum_array = array1 + array2
print(sum_array)

[ 7  9 11 13 15]


In [15]:
# appending 2 lists
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
sum_list = list1 + list2
print(sum_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
