In [2]:
print("Hello World")

Hello World


In [3]:
# importing numpy but using it as np in the whole code
import numpy as np
print("Package successfully imported!")

Package successfully imported!


In [4]:
# converting list to array
list_var = [1,2,3,4,5]
list_to_array = np.array(list_var)
print(list_to_array)
print(type(list_to_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
# converting tuple to array
tuple_var = (1,2,3,4,5)
tuple_to_array = np.array(tuple_var)
print(tuple_to_array)
print(type(tuple_to_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
# multidimensional array
array_2d = np.array([[1,2,3],[4,5,6]])
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [7]:
array_3d = np.array([[1,2,3],[4,5,6],[[1,2,3],[4,5,6]]])
print(array_3d)

[list([1, 2, 3]) list([4, 5, 6]) list([[1, 2, 3], [4, 5, 6]])]


/var/folders/p0/yyl2l2ps6fv1jt2sg6yk4m7c0000gn/T/ipykernel_32714/938592417.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array_3d = np.array([[1,2,3],[4,5,6],[[1,2,3],[4,5,6]]])


In [8]:
# adding 2 lists without the numpy
list1 = [1,2,3,4,5,9]
list2 = [6,7,8,9,10,11]
sum_list = []
length1 = len(list1)
length2 = len(list2)
min_length = min(length1, length2)
for i in range (0, min_length):
    sum_list.append(list1[i] + list2[i])
print(sum_list)

[7, 9, 11, 13, 15, 20]


In [9]:
# adding 2 lists by converting them to array with the numpy
array1 = np.array([1,2,3,4,5])
array2 = np.array([6,7,8,9,10])
sum_array = array1 + array2
print(sum_array)

[ 7  9 11 13 15]


In [10]:
# appending 2 lists
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
sum_list = list1 + list2
print(sum_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [11]:
# basic operations in the array also known as Vectorized Code
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[10,11,12],[13,14,15]])
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)

[[11 13 15]
 [17 19 21]]
[[-9 -9 -9]
 [-9 -9 -9]]
[[10 22 36]
 [52 70 90]]


In [12]:
# check in the array which value is greater than 2
array1 = np.array([1,2,3,4,5,6])
# array1[array1 > 2]
print(array1[array1 > 2])

[3 4 5 6]


In [13]:
# functions using numpy
arrange_array = np.array(list(range(1,15,2)))
print(arrange_array)

[ 1  3  5  7  9 11 13]


In [14]:
# arange() function can also be used
arrange_array = np.arange(1,15,3)
print(arrange_array)

[ 1  4  7 10 13]


In [15]:
# make an array contating only zeros - can be done using zeros() function
zero_array_1d = np.zeros(5)
print(zero_array_1d)
zero_array_2d = np.zeros([5,5])
print(zero_array_2d)

# make an array containing only ones - can be done using ones() function
one_array_1d = np.ones(5)
print(one_array_1d)
one_array_2d = np.ones([5,5])
print(one_array_2d)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
# for the values other than 1 and 0, we use full() function
print(np.full(shape = 3, fill_value = 4))   # 1D array
print(np.full(shape = 6, fill_value = 8))   # 1D array
print(np.full(shape = (4,3), fill_value = 7))   # 2D array
print(np.full(shape = (3,5), fill_value = 9))   # 2D array

[4 4 4]
[8 8 8 8 8 8]
[[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]
[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]


In [17]:
# to create any random values
print(np.random.random((3,3)))

[[0.93835198 0.03106866 0.65746607]
 [0.17684337 0.92496822 0.06198159]
 [0.1423027  0.39315229 0.03437636]]


In [18]:
# seed, random and randint
np.random.seed(2)       # random number will be generated from 2 and goes on
print(np.random.randint(low = 1, high = 15, size = 10))   # lowest value is 1, highest value is 15 and size should be 10
print(np.random.randint(low = 1, high = 15, size = (3,3)))      # creating 2D array with 3x3 matrix

[ 9 14  9  7 12  3 12  9  8  3]
[[ 2 12  6]
 [11  5 13]
 [ 5  6  8]]


In [19]:
# linspace - when the range and size of the output is known but the stepsize is unknown
arr_1 = np.linspace(1,40,6)
print(arr_1)
arr_2 = np.linspace(1,40,6, dtype = int)
print(arr_2)

[ 1.   8.8 16.6 24.4 32.2 40. ]
[ 1  8 16 24 32 40]


In [20]:
import time

In [21]:
# performing an operation for the list
list_1 = [i for i in range(200000)]
list_2 = [j**2 for j in range(200000)]
list_start_time = time.time()
list_mul = list(map(lambda x, y: x*y, list_1, list_2))
list_end_time = time.time()
print("Time Consumed: ", list_end_time - list_start_time)

Time Consumed:  0.028755903244018555


In [22]:
# using numpy
arr_1 = np.array([i for i in range(200000)])
arr_2 = np.array([j**2 for j in range(200000)])
array_start_time = time.time()
array_mul = arr_1 * arr_2
array_end_time = time.time()
print("Time Consumed: ", array_end_time - array_start_time)

Time Consumed:  0.0004799365997314453
